# Generated by Django 4.0.4 on 2022-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "org_id",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
