# Generated by Django 4.0.4 on 2022-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_app", "0003_rename_amount_paymentintent_charge_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentintent",
            name="charge_amount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
