# Generated by Django 4.0.4 on 2022-05-15 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0004_alter_paymentintent_charge_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('charge_amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_app.organization')),
            ],
            options={
                'verbose_name': 'PaymentIntent',
                'verbose_name_plural': 'PaymentIntent',
            },
        ),
        migrations.DeleteModel(
            name='PaymentIntent',
        ),
    ]
