# Generated by Django 4.0.4 on 2022-05-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_app", "0005_payment_delete_paymentintent"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="charge_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONBOARDING", "Onboarding"),
                    ("MAINTENANCE COST", "Charge for Maintenance"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
