# Generated by Django 4.0.4 on 2022-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0008_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
